async (page) => {
  await page.goto('about:blank');
  await page.unrouteAll({behavior:'ignoreErrors'});
  const results = [];
  let mode = 'success', calls = [];
  await page.route('https://example.supabase.co/**', async route => {
    const request = route.request();
    calls.push({url: request.url(), method: request.method(), body: request.postDataJSON(), authorization: request.headers().authorization});
    const headers = {'access-control-allow-origin': '*', 'access-control-allow-headers': '*'};
    if (mode === 'network') return route.abort();
    if (mode === 'timeout') return;
    if (mode === 'expired') return route.fulfill({status: 401, headers, json: {code: 'bad_jwt'}});
    if (mode === 'limited') return route.fulfill({status: 429, headers, json: {code: 'over_email_send_rate_limit'}});
    if (mode === 'weak' && request.method() === 'PUT') return route.fulfill({status: 422, headers, json: {code: 'weak_password'}});
    await route.fulfill({status: 200, headers, json: request.url().includes('/recover?') ? {} : {id: 'fixture-user', email: 'fixture@example.com'}});
  });
  const assert = (value, message) => {if (!value) throw new Error(message);};
  async function status(text) {await page.getByRole('status').filter({hasText: text}).waitFor({state: 'visible'});}
  const root = 'http://127.0.0.1:8765/recovery.html';
  const callback = '#access_token=fixture-token&refresh_token=fixture-refresh&type=recovery';
  async function open(suffix = '') {await page.goto(root + suffix);}
  await open();
  await page.getByLabel('メールアドレス', {exact:true}).fill('fixture@example.com');
  await page.getByRole('button', {name:'再設定メールを送信する'}).click();
  await status('登録済みのアドレスであれば');
  const send = calls.find(call => call.url.includes('/recover?'));
  assert(send.url.endsWith('redirect_to=' + encodeURIComponent(root)), 'Wrong redirect URL');
  assert(send.body.email === 'fixture@example.com' && !send.authorization, 'Wrong email request');
  results.push('PASS email request and explicit redirect');
  await open(callback);
  await status('確認できました');
  assert(page.url() === root, 'Token remains in URL');
  assert(await page.getByText('対象アカウント：fixture@example.com').isVisible(), 'Account missing');
  const password = page.getByLabel('新しいパスワード', {exact:true});
  const confirmation = page.getByLabel('新しいパスワード（確認）', {exact:true});
  const update = page.getByRole('button', {name:'パスワードを再設定する', exact:true});
  await password.fill('fixture-password'); await confirmation.fill('different-password'); await update.click();
  await status('一致しません');
  assert(!calls.some(call=>call.method==='PUT'), 'Mismatch sent to API');
  results.push('PASS mismatch rejected locally');
  mode = 'weak'; await confirmation.fill('fixture-password'); await update.click();
  await status('より長く');
  assert(await update.isEnabled(), 'Button stuck after rejection');
  assert(await password.inputValue() === '', 'Password not cleared on rejection');
  results.push('PASS server rejection clears password and restores button');
  mode = 'success'; await password.fill('fixture-password'); await confirmation.fill('fixture-password'); await update.click();
  await status('パスワードを再設定しました');
  const put = calls.find(call=>call.method==='PUT');
  assert(put.authorization === 'Bearer fixture-token', 'Wrong recovery authorization');
  assert(Object.keys(put.body).join(',') === 'password', 'Unexpected mutation');
  assert(!await page.locator('#reset-section').isVisible(), 'Reset form remains visible');
  const storage = await page.evaluate(()=>JSON.stringify([Object.entries(localStorage), Object.entries(sessionStorage)]));
  assert(!storage.includes('fixture-token') && !storage.includes('fixture-password'), 'Credentials persisted');
  results.push('PASS successful update and credential cleanup');
  mode = 'expired'; await open(callback); await status('期限切れ');
  assert(await page.locator('#request-section').isVisible(), 'Cannot request a replacement');
  results.push('PASS expired session');
  mode = 'success'; calls = []; await open('#error=access_denied&error_code=otp_expired'); await status('期限切れ');
  assert(calls.length===0 && page.url()===root, 'Error callback sent a request or retained hash');
  await open('#access_token=fixture-token&type=signup'); await status('期限切れ');
  assert(calls.length===0, 'Non-recovery token accepted');
  results.push('PASS expired callback and wrong flow rejected');
  mode = 'limited'; await open(); await page.getByLabel('メールアドレス', {exact:true}).fill('fixture@example.com');
  await page.getByRole('button', {name:'再設定メールを送信する'}).click(); await status('回数制限');
  results.push('PASS rate limit');
  mode = 'network'; await open(callback); await status('通信できません');
  results.push('PASS network failure');
  mode = 'success'; await open(callback); await status('確認できました');
  mode = 'timeout'; await password.fill('fixture-password'); await confirmation.fill('fixture-password'); await update.click();
  await status('変更が済んでいる可能性');
  assert(await update.isEnabled(), 'Button stuck after timeout');
  results.push('PASS actual 15-second update timeout');
  mode = 'success'; await page.reload();
  assert(await page.locator('#request-section').isVisible() && !await page.locator('#reset-section').isVisible(), 'Reload reused recovery token');
  await page.setViewportSize({width:390,height:844});
  await page.screenshot({path:'output/playwright/recovery-mobile.png', fullPage:true});
  assert(await page.evaluate(()=>document.documentElement.scrollWidth <= innerWidth), 'Mobile horizontal overflow');
  results.push('PASS reload and mobile layout');
  return results;
}
